-- Material Hierarchy Table
-- This table stores the hierarchical relationship between Grade of Material, Material Kind, Manufacturer, and Brand Name

CREATE TABLE IF NOT EXISTS material_hierarchy (
  id INT AUTO_INCREMENT PRIMARY KEY,
  grade_of_material VARCHAR(100) NOT NULL,
  material_kind VARCHAR(100) NOT NULL,
  manufacturer VARCHAR(100) NOT NULL,
  brand_name VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_grade (grade_of_material),
  INDEX idx_material_kind (material_kind),
  INDEX idx_manufacturer (manufacturer),
  INDEX idx_brand (brand_name)
);

-- Insert VIRGIN materials
-- VIRGIN -> FBB
INSERT INTO material_hierarchy (grade_of_material, material_kind, manufacturer, brand_name) VALUES
('VIRGIN', 'FBB', 'ITC', 'CYBER XL'),
('VIRGIN', 'FBB', 'ITC', 'PEARL XL'),
('VIRGIN', 'FBB', 'ITC', 'OTHERS'),
('VIRGIN', 'FBB', 'EMAMI', 'MAXOFOLD'),
('VIRGIN', 'FBB', 'EMAMI', 'OTHERS'),
('VIRGIN', 'FBB', 'JK', 'TUFFCOTE'),
('VIRGIN', 'FBB', 'JK', 'ENDURA'),
('VIRGIN', 'FBB', 'JK', 'TUFFPAC'),
('VIRGIN', 'FBB', 'JK', 'OTHERS'),
('VIRGIN', 'FBB', 'TNPL', 'AURA FOLD PLUS'),
('VIRGIN', 'FBB', 'TNPL', 'AURA FOLD PREMIUM'),
('VIRGIN', 'FBB', 'TNPL', 'AURA FOLD ECO'),
('VIRGIN', 'FBB', 'TNPL', 'OTHERS'),
('VIRGIN', 'FBB', 'CENTURY', 'PRIMA PLUS'),
('VIRGIN', 'FBB', 'CENTURY', 'PRIMA FOLD'),
('VIRGIN', 'FBB', 'CENTURY', 'OTHERS'),
('VIRGIN', 'FBB', 'IMPORTED', 'OTHERS'),
('VIRGIN', 'FBB', 'OTHERS', 'OTHERS'),

-- VIRGIN -> SBS
('VIRGIN', 'SBS', 'ITC', 'SAPHIRE GRAPHIC'),
('VIRGIN', 'SBS', 'ITC', 'CARTA LUMINA'),
('VIRGIN', 'SBS', 'ITC', 'OTHERS'),
('VIRGIN', 'SBS', 'EMAMI', 'GLAMKOT'),
('VIRGIN', 'SBS', 'EMAMI', 'OTHERS'),
('VIRGIN', 'SBS', 'JK', 'ULTIMA'),
('VIRGIN', 'SBS', 'JK', 'PLATINA'),
('VIRGIN', 'SBS', 'JK', 'OTHERS'),
('VIRGIN', 'SBS', 'TNPL', 'AURA BRILLIANT'),
('VIRGIN', 'SBS', 'TNPL', 'OTHERS'),
('VIRGIN', 'SBS', 'CENTURY', 'OMEGA PLUS'),
('VIRGIN', 'SBS', 'CENTURY', 'OMEGA STAR'),
('VIRGIN', 'SBS', 'CENTURY', 'OTHERS'),
('VIRGIN', 'SBS', 'IMPORTED', 'OTHERS'),
('VIRGIN', 'SBS', 'OTHERS', 'OTHERS'),

-- VIRGIN -> CUP STOCK
('VIRGIN', 'CUP STOCK', 'OTHERS', 'OTHERS'),

-- VIRGIN -> OTHERS
('VIRGIN', 'OTHERS', 'OTHERS', 'OTHERS'),

-- Insert RECYCLED materials
-- RECYCLED -> GREYBACK
('RECYCLED', 'GREYBACK', 'NR', 'OTHERS'),
('RECYCLED', 'GREYBACK', 'GAYATRI', 'OTHERS'),
('RECYCLED', 'GREYBACK', 'MEHALI', 'OTHERS'),
('RECYCLED', 'GREYBACK', 'KHANNA', 'OTHERS'),
('RECYCLED', 'GREYBACK', 'TULSI', 'OTHERS'),
('RECYCLED', 'GREYBACK', 'AADITYA', 'OTHERS'),
('RECYCLED', 'GREYBACK', 'LEMIT-ITC', 'OTHERS'),
('RECYCLED', 'GREYBACK', 'ITC', 'OTHERS'),
('RECYCLED', 'GREYBACK', '3M', 'OTHERS'),
('RECYCLED', 'GREYBACK', 'OTHERS', 'OTHERS'),

-- RECYCLED -> WHITE BACK
('RECYCLED', 'WHITE BACK', 'GAYATRI', 'OTHERS'),
('RECYCLED', 'WHITE BACK', 'OTHERS', 'OTHERS'),

-- RECYCLED -> LWC GREY BACK
('RECYCLED', 'LWC GREY BACK', 'MEHALI', 'OTHERS'),
('RECYCLED', 'LWC GREY BACK', 'OTHERS', 'OTHERS'),

-- RECYCLED -> OTHERS
('RECYCLED', 'OTHERS', 'OTHERS', 'OTHERS'),

-- Insert METPET materials
('METPET', 'FBB', 'ALL', 'FROM VIRGIN AND RECYCLED'),
('METPET', 'FBB', 'ALL', 'OTHERS'),
('METPET', 'SBS', 'ALL', 'FROM VIRGIN AND RECYCLED'),
('METPET', 'SBS', 'ALL', 'OTHERS'),
('METPET', 'GREYBACK', 'ALL', 'FROM VIRGIN AND RECYCLED'),
('METPET', 'GREYBACK', 'ALL', 'OTHERS'),
('METPET', 'WHITE BACK', 'ALL', 'FROM VIRGIN AND RECYCLED'),
('METPET', 'WHITE BACK', 'ALL', 'OTHERS'),
('METPET', 'LWC GREY BACK', 'ALL', 'FROM VIRGIN AND RECYCLED'),
('METPET', 'LWC GREY BACK', 'ALL', 'OTHERS'),
('METPET', 'OTHERS', 'OTHERS', 'OTHERS'),

-- Insert COATED PAPER materials
('COATED PAPER', 'BOTH SIDE COATED', 'BILT', 'OTHERS'),
('COATED PAPER', 'BOTH SIDE COATED', 'OTHERS', 'OTHERS'),
('COATED PAPER', 'ONE SIDE COATED', 'IMPORTED', 'OTHERS'),
('COATED PAPER', 'ONE SIDE COATED', 'OTHERS', 'OTHERS'),
('COATED PAPER', 'OTHERS', 'OTHERS', 'OTHERS'),

-- Insert MAPLITHO materials
('MAPLITHO', 'MAPLITHO', 'VARIOUS MILLS', 'OTHERS'),
('MAPLITHO', 'MAPLITHO', 'OTHERS', 'OTHERS'),
('MAPLITHO', 'CREAMWOVE', 'VARIOUS MILLS', 'OTHERS'),
('MAPLITHO', 'CREAMWOVE', 'OTHERS', 'OTHERS'),
('MAPLITHO', 'OTHERS', 'OTHERS', 'OTHERS'),

-- Insert HIGH VALUE PAPER materials
('HIGH VALUE PAPER', 'BIBLE PAPER', 'IMPORTED', 'OTHERS'),
('HIGH VALUE PAPER', 'BIBLE PAPER', 'ITC', 'OTHERS'),
('HIGH VALUE PAPER', 'BIBLE PAPER', 'PUDUMJEE', 'OTHERS'),
('HIGH VALUE PAPER', 'BIBLE PAPER', 'OTHERS', 'OTHERS'),
('HIGH VALUE PAPER', 'OTHERS', 'OTHERS', 'OTHERS'),

-- Insert PLASTIC SHEETS materials
('PLASTIC SHEETS', 'PP', 'OTHERS', 'OTHERS'),
('PLASTIC SHEETS', 'PET', 'OTHERS', 'OTHERS'),
('PLASTIC SHEETS', 'PVC', 'OTHERS', 'OTHERS'),
('PLASTIC SHEETS', 'OTHERS', 'OTHERS', 'OTHERS'),

-- Insert PE COATED materials
('PE COATED', 'FBB', 'ALL', 'FROM VIRGIN AND RECYCLED'),
('PE COATED', 'FBB', 'ALL', 'OTHERS'),
('PE COATED', 'SBS', 'ALL', 'FROM VIRGIN AND RECYCLED'),
('PE COATED', 'SBS', 'ALL', 'OTHERS'),
('PE COATED', 'GREYBACK', 'ALL', 'FROM VIRGIN AND RECYCLED'),
('PE COATED', 'GREYBACK', 'ALL', 'OTHERS'),
('PE COATED', 'WHITE BACK', 'ALL', 'FROM VIRGIN AND RECYCLED'),
('PE COATED', 'WHITE BACK', 'ALL', 'OTHERS'),
('PE COATED', 'LWC GREY BACK', 'ALL', 'FROM VIRGIN AND RECYCLED'),
('PE COATED', 'LWC GREY BACK', 'ALL', 'OTHERS'),
('PE COATED', 'OTHERS', 'OTHERS', 'OTHERS'),

-- Insert KRAFT materials
('KRAFT', 'NATURAL SHADE', 'GODAVARI', 'OTHERS'),
('KRAFT', 'NATURAL SHADE', 'PADMAVATI', 'OTHERS'),
('KRAFT', 'NATURAL SHADE', 'BEST', 'OTHERS'),
('KRAFT', 'NATURAL SHADE', 'AJIT', 'OTHERS'),
('KRAFT', 'NATURAL SHADE', 'DEVANG', 'OTHERS'),
('KRAFT', 'NATURAL SHADE', 'LAXMI', 'OTHERS'),
('KRAFT', 'NATURAL SHADE', 'SUNSHINE', 'OTHERS'),
('KRAFT', 'NATURAL SHADE', 'GAYATRISHAKTI', 'OTHERS'),
('KRAFT', 'NATURAL SHADE', 'WEST ROCK', 'OTHERS'),
('KRAFT', 'NATURAL SHADE', 'SHREE GAJANAN', 'OTHERS'),
('KRAFT', 'NATURAL SHADE', 'ARYAN', 'OTHERS'),
('KRAFT', 'NATURAL SHADE', 'GANGA', 'OTHERS'),
('KRAFT', 'NATURAL SHADE', 'OTHERS', 'OTHERS'),
('KRAFT', 'GOLD SHADE', 'PADMAVATI', 'OTHERS'),
('KRAFT', 'GOLD SHADE', 'OTHERS', 'OTHERS'),
('KRAFT', 'OTHERS', 'OTHERS', 'OTHERS'),

-- Insert OTHERS materials
('OTHERS', 'OTHERS', 'OTHERS', 'OTHERS');
